Data_EraE: 
    path: "/eos/home-e/evourlio/HiggsDNA/samples_data_2022postEE_RunE/merged/Run2022E/NOTAG_merged.parquet"
    lumi: 5672 # /pb

Data_EraF: 
    path: "/eos/home-e/evourlio/HiggsDNA/samples_data_2022postEE_RunFG/merged/Run2022F/NOTAG_merged.parquet"
    lumi: 17610 # /pb

Data_EraG: 
    path: "/eos/home-e/evourlio/HiggsDNA/samples_data_2022postEE_RunFG/merged/Run2022G/NOTAG_merged.parquet"
    lumi: 3055 # /pb

#signal
#ggF HH xs = 0.03413 pb (@13.6 TeV) https://twiki.cern.ch/twiki/bin/view/LHCPhysics/LHCHWGHH?redirectedfrom=LHCPhysics.LHCHXSWGHH#Latest_recommendations_for_gluon
#H -> gg BR = 2.270E-03 https://twiki.cern.ch/twiki/bin/view/LHCPhysics/CERNYellowReportPageBR
#H -> bb BR = 5.824E-01
#Sample xs = 2*(ggF HH xs)(H -> gg BR)((H -> bb BR))
GluGluToHH: 
    path: "/eos/home-e/evourlio/HiggsDNA/samples_mcSignal_2022postEE/merged/GluGluToHH/NOTAG_merged.parquet"
    xs: 0.00009
    
#resonant background
#H prod XS: https://twiki.cern.ch/twiki/bin/view/LHCPhysics/LHCHWG136TeVxsec_extrap#ggF_N3LO_QCD_NLO_EW
#H -> gg BR = 2.270E-03: https://twiki.cern.ch/twiki/bin/view/LHCPhysics/CERNYellowReportPageBR#Higgs_2_gauge_bosons
GluGluHToGG: 
    path: "/eos/home-e/evourlio/HiggsDNA/samples_mcSingleHiggs_2022postEE/merged/GluGluHToGG/NOTAG_merged.parquet"
    xs: 0.1186 #XS = 52.23

ttHToGG: 
    path: "/eos/home-e/evourlio/HiggsDNA/samples_mcSingleHiggs_2022postEE/merged/ttHToGG/NOTAG_merged.parquet"
    xs: 0.0013 #XS = 0.57

VBFHToGG: 
    path: "/eos/home-e/evourlio/HiggsDNA/samples_mcSingleHiggs_2022postEE/merged/VBFHToGG/NOTAG_merged.parquet"
    xs: 0.00926 #XS = 4.078

VHToGG: 
    path: "/eos/home-e/evourlio/HiggsDNA/samples_mcSingleHiggs_2022postEE/merged/VHToGG/NOTAG_merged.parquet"
    xs: 0.00545 #XS = 1.457 + 0.9439 = 2.401

#continuous background
GGJets: 
    path: "/eos/home-e/evourlio/HiggsDNA/samples_mcGGJets_2022postEE/merged/GGJets/NOTAG_merged.parquet"
    xs: 88.75 #https://xsdb-temp.app.cern.ch/xsdb/?columns=67108863&currentPage=0&pageSize=10&searchQuery=DAS=%20%20GG-Box-3Jets_MGG-80_13p6TeV_sherpa
    
# TTGG:
    # path: "/eos/home-x/xuyan/public/HH2BBGG/parquet_central/Run3_2022postEE/TTGG.parquet"
    # xs: 0.02391

# DDQCDGJets:
    # path: "/eos/home-x/xuyan/public/HH2BBGG/parquet_central/Run3_2022postEE/DDQCDGJET.parquet"
    # xs: 1