Data_EraE: 
    path: "/home/users/xuyan/HH2ggbb/parquets/v2_PNet/2022postEE/Run2022E_with_full_PNet_info.parquet"
    lumi: 5672 # /pb

Data_EraF: 
    path: "/home/users/xuyan/HH2ggbb/parquets/v2_PNet/2022postEE/Run2022F_with_full_PNet_info.parquet"
    lumi: 17610 # /pb

Data_EraG: 
    path: "/home/users/xuyan/HH2ggbb/parquets/v2_PNet/2022postEE/Run2022G_with_full_PNet_info.parquet"
    lumi: 3055 # /pb

#signal
#ggF HH xs = 0.03413 pb (@13.6 TeV) https://twiki.cern.ch/twiki/bin/view/LHCPhysics/LHCHWGHH?redirectedfrom=LHCPhysics.LHCHXSWGHH#Latest_recommendations_for_gluon
#H -> gg BR = 2.270E-03 https://twiki.cern.ch/twiki/bin/view/LHCPhysics/CERNYellowReportPageBR
#H -> bb BR = 5.824E-01
#Sample xs = 2*(ggF HH xs)(H -> gg BR)((H -> bb BR))
GluGluToHH: 
    path: "/home/users/xuyan/HH2ggbb/parquets/v2_PNet/2022postEE/GluGluToHH_with_full_PNet_info.parquet"
    xs: 0.00009
    
#resonant background
#H prod XS: https://twiki.cern.ch/twiki/bin/view/LHCPhysics/LHCHWG136TeVxsec_extrap#ggF_N3LO_QCD_NLO_EW
#H -> gg BR = 2.270E-03: https://twiki.cern.ch/twiki/bin/view/LHCPhysics/CERNYellowReportPageBR#Higgs_2_gauge_bosons
GluGluHToGG: 
    path: "/home/users/xuyan/HH2ggbb/parquets/v2_PNet/2022postEE/GluGluHToGG_with_full_PNet_info.parquet"
    xs: 0.1186 #XS = 52.23

ttHToGG: 
    path: "/home/users/xuyan/HH2ggbb/parquets/v2_PNet/2022postEE/ttHToGG_with_full_PNet_info.parquet"
    xs: 0.0013 #XS = 0.57

VBFHToGG: 
    path: "/home/users/xuyan/HH2ggbb/parquets/v2_PNet/2022postEE/VBFHToGG_with_full_PNet_info.parquet"
    xs: 0.00926 #XS = 4.078

VHToGG: 
    path: "/home/users/xuyan/HH2ggbb/parquets/v2_PNet/2022postEE/VHToGG_with_full_PNet_info.parquet"
    xs: 0.00545 #XS = 1.457 + 0.9439 = 2.401

#continuous background
GGJets: 
    path: "/home/users/xuyan/HH2ggbb/parquets/v2_PNet/2022postEE/GGJets_with_full_PNet_info.parquet"
    xs: 88.75 #https://xsdb-temp.app.cern.ch/xsdb/?columns=67108863&currentPage=0&pageSize=10&searchQuery=DAS=%20%20GG-Box-3Jets_MGG-80_13p6TeV_sherpa
    
TTGG:
    path: "/home/users/xuyan/HH2ggbb/parquets/v2_PNet/2022postEE/TTGG_with_full_PNet_info.parquet"
    xs: 0.02391

DDQCDGJets:
    path: "/home/users/xuyan/HH2ggbb/parquets/v2_PNet/2022postEE/DDQCDGJET_with_full_PNet_info.parquet"
    xs: 1